name: Haskell CI

on: 
  pull_request:
    branches: ["*"]
  push:
    branches: [master]
  schedule:
  - cron: "00 12 * * *"

jobs:
  build-deps:
    continue-on-error: ${{ matrix.falliable }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        ghc: ["8.8.4", "8.10.7", "9.0.2", "9.2.3"]
        falliable: [false]
    env:
      STACK_YAML: "stack-${{ matrix.ghc }}.yaml"

    steps:

    - uses: actions/checkout@v2
    - name: Cache ~/.stack
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: ~/.stack
        # An explicit key for restoring and saving the cache
        key: ${{runner.os}}-${{github.ref}}-stack-global-${{ matrix.ghc }}-${{ hashFiles('stack.yaml.lock') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{runner.os}}-master-stack-global-${{ matrix.ghc }}
          ${{runner.os}}-master-stack-global

    - name: Cache ~/.cabal
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: ~/.cabal
        # An explicit key for restoring and saving the cache
        key: ${{runner.os}}-${{github.ref}}-cabal-${{ matrix.ghc }}-${{ hashFiles('stack.yaml.lock') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{runner.os}}-master-cabal-${{ matrix.ghc }}
          ${{runner.os}}-master-cabal

    - name: Cache ~/.ghc
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: ~/.ghc
        # An explicit key for restoring and saving the cache
        key: ${{runner.os}}-${{github.ref}}-ghc-${{ matrix.ghc }}-${{ hashFiles('stack.yaml.lock') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{runner.os}}-master-ghc-${{ matrix.ghc }}
          ${{runner.os}}-master-ghc

    - name: Cache .stack-work
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: .stack-work
        # An explicit key for restoring and saving the cache
        key: ${{runner.os}}-${{github.ref}}-stack-work-${{ matrix.ghc }}-${{ hashFiles('stack.yaml.lock') }}
        restore-keys: |
          ${{runner.os}}-master-stack-work-${{ matrix.ghc }}
          ${{runner.os}}-master-stack-work

    - uses: haskell/actions/setup@v1.1.7
      with:
        enable-stack: true

    - name: Install dependencies
      run: |
        pwd
        ls
        stack --no-terminal build --test --no-run-tests --only-dependencies

  build:
    continue-on-error: ${{ matrix.falliable }}
    needs:
    - build-deps
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        ghc: ["8.8.4", "8.10.7", "9.0.2"]
        falliable: [false]
        include:
          - ghc: "9.2.1"
            falliable: true
    env:
      STACK_YAML: "stack-${{ matrix.ghc }}.yaml"

    steps:

    - uses: actions/checkout@v2
    - name: Cache ~/.stack
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: ~/.stack
        # An explicit key for restoring and saving the cache
        key: ${{runner.os}}-${{github.ref}}-stack-global-${{ matrix.ghc }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**/*.hs') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{runner.os}}-${{github.ref}}-stack-global-${{ matrix.ghc }}-${{ hashFiles('stack.yaml.lock') }}
          ${{runner.os}}-${{github.ref}}-stack-global-${{ matrix.ghc }}
          ${{runner.os}}-master-stack-global

    - name: Cache ~/.cabal
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: ~/.cabal
        # An explicit key for restoring and saving the cache
        key: ${{runner.os}}-${{github.ref}}-cabal-${{ matrix.ghc }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**/*.hs') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{runner.os}}-${{github.ref}}-cabal-${{ matrix.ghc }}-${{ hashFiles('stack.yaml.lock') }}
          ${{runner.os}}-${{github.ref}}-cabal-${{ matrix.ghc }}
          ${{runner.os}}-master-cabal

    - name: Cache ~/.ghc
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: ~/.ghc
        # An explicit key for restoring and saving the cache
        key: ${{runner.os}}-${{github.ref}}-ghc-${{ matrix.ghc }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**/*.hs') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{runner.os}}-${{github.ref}}-ghc-${{ matrix.ghc }}-${{ hashFiles('stack.yaml.lock') }}
          ${{runner.os}}-${{github.ref}}-ghc-${{ matrix.ghc }}
          ${{runner.os}}-master-ghc

    - name: Cache .stack-work
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: .stack-work
        # An explicit key for restoring and saving the cache
        key: ${{runner.os}}-${{github.ref}}-stack-work-${{ matrix.ghc }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**/*.hs') }}
        restore-keys: |
          ${{runner.os}}-${{github.ref}}-stack-work-${{ matrix.ghc }}-${{ hashFiles('stack.yaml.lock') }}
          ${{runner.os}}-${{github.ref}}-stack-work-${{ matrix.ghc }}
          ${{runner.os}}-master-stack-work
    - uses: haskell/actions/setup@v1.1.7
      with:
        enable-stack: true
      
    - name: Build
      run: |
        stack --no-terminal build --test --no-run-tests

  test:
    continue-on-error: ${{ matrix.falliable }}
    needs:
    - build-deps
    - build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        ghc: ["8.8.4", "8.10.7", "9.0.2"]
        falliable: [false]
        include:
          - ghc: "9.2.1"
            falliable: true
    env:
      STACK_YAML: "stack-${{ matrix.ghc }}.yaml"
  
    steps:

    - uses: actions/checkout@v2
    - name: Cache ~/.stack
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: ~/.stack
        # An explicit key for restoring and saving the cache
        key: ${{runner.os}}-${{github.ref}}-stack-global-${{ matrix.ghc }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**/*.hs') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{runner.os}}-${{github.ref}}-stack-global-${{ matrix.ghc }}-${{ hashFiles('stack.yaml.lock') }}
          ${{runner.os}}-${{github.ref}}-stack-global-${{ matrix.ghc }}
          ${{runner.os}}-master-stack-global

    - name: Cache ~/.cabal
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: ~/.cabal
        # An explicit key for restoring and saving the cache
        key: ${{runner.os}}-${{github.ref}}-cabal-${{ matrix.ghc }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**/*.hs') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{runner.os}}-${{github.ref}}-cabal-${{ matrix.ghc }}-${{ hashFiles('stack.yaml.lock') }}
          ${{runner.os}}-${{github.ref}}-cabal-${{ matrix.ghc }}
          ${{runner.os}}-master-cabal

    - name: Cache ~/.ghc
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: ~/.ghc
        # An explicit key for restoring and saving the cache
        key: ${{runner.os}}-${{github.ref}}-ghc-${{ matrix.ghc }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**/*.hs') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{runner.os}}-${{github.ref}}-ghc-${{ matrix.ghc }}-${{ hashFiles('stack.yaml.lock') }}
          ${{runner.os}}-${{github.ref}}-ghc-${{ matrix.ghc }}
          ${{runner.os}}-master-ghc

    - name: Cache .stack-work
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: .stack-work
        # An explicit key for restoring and saving the cache
        key: ${{runner.os}}-${{github.ref}}-stack-work-${{ matrix.ghc }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**/*.hs') }}
        restore-keys: |
          ${{runner.os}}-${{github.ref}}-stack-work-${{ matrix.ghc }}-${{ hashFiles('stack.yaml.lock') }}
          ${{runner.os}}-${{github.ref}}-stack-work-${{ matrix.ghc }}
          ${{runner.os}}-master-stack-work
    - uses: haskell/actions/setup@v1.1.7
      with:
        enable-stack: true

    - name: Run tests
      run: stack --no-terminal build --test
